# Generated by Django 5.2.4 on 2026-05-16 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Entity ID')),
                ('user_text', models.TextField(help_text='Kullanıcının ruh halini tarif eden serbest metin.', verbose_name='Ham Kullanıcı Girdisi')),
                ('detected_mood', models.CharField(db_index=True, help_text='Gemini tarafından çıkarılan ana ruh hali etiketi.', max_length=50, verbose_name='Tespit Edilen Ruh Hali')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma Zamanı')),
            ],
            options={
                'verbose_name': 'Mood Girdisi',
                'verbose_name_plural': 'Mood Girdileri',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='mood_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='SongRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Entity ID')),
                ('title', models.CharField(max_length=200, verbose_name='Şarkı Adı')),
                ('artist', models.CharField(db_index=True, max_length=200, verbose_name='Sanatçı')),
                ('reason', models.TextField(help_text="Gemini'nin bu şarkıyı önerme sebebi.", verbose_name='AI Gerekçesi')),
                ('album_cover_url', models.URLField(blank=True, null=True, verbose_name='Albüm Kapağı URL')),
                ('mood_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.moodentry', verbose_name='Parent Mood Entry')),
            ],
            options={
                'verbose_name': 'Şarkı Önerisi',
                'verbose_name_plural': 'Şarkı Önerileri',
                'ordering': ('title',),
            },
        ),
    ]
